##
## EPITECH PROJECT, 2018
## libmy
## File description:
## tests
##

CC	=	gcc

CFLAGS	+=	-g3
CFLAGS	+=	-I../includes/
CFLAGS	+=	-W -Wall -Wextra

LDFLAGS	+=	-L../ -lmy

.c:
	$(CC) -o $@ $< $(CFLAGS) $(LDFLAGS)